Note taking
bhtibrewal/artsy-stream pull request #7
Opened 2022-04-06 18:13 UTC by bhtibrewal

Added note-taking to each video 
Created custom Controller

Pages to check
- NotesController.js
- NotesForm.js
- NotesSection.js
- removeAllNotesForVideo.js
- addNewNoteToVideo.js
- deleteNotefromVideo.js

2022-04-06 18:46 UTC, Naman-Saxena1 requested changes
Code looks fine 
But I have 2 suggestions:
1. Clear Notes button is not working, you can cross check
2. Contrast ratio of notes is too low 
![Screenshot (1)](https://user-images.githubusercontent.com/90456667/162046546-bbde1960-4406-400c-b2ca-b9b6f678c602.png)

2022-04-07 13:13 UTC, Ankur9669 approved these changes
The code and the UI both are looking good,

![image](https://user-images.githubusercontent.com/65125998/162206613-356472df-8107-400c-a74c-7c96183614a6.png)

On clicking clear notes button the notes ae not getting cleared

You can correct that than you can merge

2022-04-07 13:13 UTC, Ankur9669 commented on src/backend/controllers/AuthController.js
> +      notesManagement: [],
Appreciation: Nice work on the controller part

2022-04-07 13:13 UTC, Ankur9669 commented on src/pages/emptylist_page/EmptyListPage.jsx
> +            <span> Explore</span>
Could use p tag here

2022-04-07 13:13 UTC, Ankur9669 commented on src/pages/video_page/video_page.css
> +  max-width: 800px;
can use relative units

2022-04-07 13:13 UTC, Ankur9669 commented on src/server.js
>  }
Nice work here

2022-04-07 16:49 UTC, merged